// <auto-generated />
namespace CinemaPlanet.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RelationshipChangedToOneToManeBetweenRoleAndUserTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationshipChangedToOneToManeBetweenRoleAndUserTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202103281710470_RelationshipChangedToOneToManeBetweenRoleAndUserTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
